language: node_js
os: linux
dist: xenial
group: travis_lts

addons:
  chrome: stable

node_js:
  - '10'

notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
      - forrest.li@kitware.com
      - stephen.aylward@kitware.com
    on_success: change
    on_failure: always

cache:
  directories:
    - "$HOME/.npm"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgif-dev
  - npm i -g npm@6.0.1

install:
  - npm ci

script:
  - if [ "$TRAVIS_EVENT_TYPE" == "push" ] && [ "$TRAVIS_BRANCH" == "master" ]; then ./build/travis-release.sh; fi
